name: 'CM Backport PR'
author: 'cristiammercado'
description: 'Backport from a branch to another using a pull request.'
inputs:
  token:
    description: 'Personal access token (PAT) if you dont want to use the default value for this field.'
    required: false
    default: '${{ github.token }}'
  pr-from-branch:
    description: 'The name of the branch where your changes are implemented. This should be an existing branch on the current repository.'
    required: false
    default: main
  pr-to-branch:
    description: 'The name of the branch you want the changes pulled into. This should be an existing branch on the current repository.'
    required: false
    default: next
  pr-title:
    description: 'The title of the new pull request.'
    required: false
    default: ''
  pr-hotfix-number:
    description: 'The number of the hotfix.'
    required: true
    default: '${{github.event.pull_request.number}}'
  pr-body:
    description: 'The contents of the pull request.'
    required: false
    default: ''
  pr-fail-if-exists:
    description: 'If there is already a PR that matches the configured branches, with this option you can control whether you want the action to throw an error.'
    required: false
    default: 'true'
  pr-update-if-exists:
    description: 'If there is already a PR that matches the configured branches, with this option you can update that PR with the new content.'
    required: false
    default: 'false'
  maintainer-can-modify:
    description: 'Indicates whether maintainers can modify the pull request.'
    required: false
    default: 'false'
outputs:
  pr-number:
    description: 'Pull request number.'
  pr-url:
    description: 'Pull request URL.'
  pr-sha:
    description: 'Commit SHA if merge-pr-after-created is true'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'purple'
